server:
    servlet:
        context-path: /anime/api
    error:
        include-stacktrace: never

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        Hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect